version: '3.3'
services:
  db:
    container_name: shopper-mysql
    image: mysql:5.7
    command: --lower_case_table_names=1
    restart: always
    environment:
      MYSQL_DATABASE: 'shopper'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'shopper_user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'shopper@pass'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
      # PORT
      MYSQL_TCP_PORT: '3309'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3309:3309'
    expose:
      # Opens port 3306 on the container
      - '3309'
 # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: